name: CI model to Dockerhub

on:
  pull_request:
    branches:
      - Dev

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t caradepanocho18/deploy-breast-cancer:v1 .

      - name: Docker push to Dockerhub
        run: docker push caradepanocho18/deploy-breast-cancer:v1
